travis:
  secure:
    BINSTAR_TOKEN: p/Eh7KhqYS5mhxGB5oqYCy3dlxlC7wvu/ap+Q7M7IUNoBuRVebYyWP5WJggNw5Qon4o32/Zxju9wBsMfUL/NryF7YUzRwtstbkxbNNydPJjEPLYrcIUXPsJXXOnqM5yNuYDAknvlPWvbyxGZ30RipEkY/NA867Flu/07P8069jCXbbKjcmxFFeEuvOLi8zLm5ESoMOOHIvn9g3UAFpH920y0c9QmDyEYWSMU5crZ6ag5ABHO1RnyE/xUD6YnJ7BNYKOUj1petg7XISa4GN8pEWDo687ti8V+1ImCwHHtiV1mV1aJR8m7LQMfZUZRHDrv1bwwcQzi4cOr+8qPFNNSfQ4mMLMfvS2ZGmJeHAV6Hj+IhFBz7R7iDBhKpIe2M/tuDvW/W2wN91w943oIP6Z7uwsln8iIX3iY8seK/pt6UNWxVnKizx/lij7dK3LDhbQX4/MhgwP1q2Rla99MSF8ITRC2EGes9Bik5CSafN4FgVQCVclbXyA+kd9xZrJxORZOU8E6nNeXq0RH4jyK3uKifyMnweZ8H2dldLCgbNTFXp8Ghgg4U7YWjI4vMGEkTBGyGhnI2NPwVjyEGbXxT+CTFnNrL5num0Y4eZAclRpw1lrTdMvu+z1xGTXjRvKW3gsoA7TLjywxebwtchbdPN9fHNzWkGIRpUlPbmyweO5N//A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
