travis:
  secure:
    BINSTAR_TOKEN: qzgWmRpiWziCsqA7aX6y2M9I3amZfyNc0JSyMyfzSfgJd4fKl6S6wdr/iUPuEDKM9pm5ynembR0aT0Wl6Ruaq4EZGKKHlN+zD0uxbkSVUT7BW/8jAUT1XgBvt7anpbP64dAE9MPRk2u14a307ovL11FW1Dq/8oyinflL+mxIE6gFS2DxYvZRI0ocFJ+UNKHup31hZ8Cl4rGBLF7pds8wtv7yATKreAPYMk2fi74ZhJZ/uJuClKgpIElFRMF/ew3EEzoVp/PhEm6Q1apdIfJaXKKIHtoLOLOPNUWkDLF2xtnjHkVnKKfgzvwCRGidLFX0m9dTAbdpq9qsEoQeI7UNemigtrFVkGX+VpfA+AS4Xwl0zJO0zVULrJzAahc+IW0acLa8On8t2x1TrgMT22dB5PP3Y6ndkQADuELcaMj+O2sNfjoezC2KjQdDxMZVgVPkjfSdgL07CysmhvSXPqsFZ7GlYEJydkkmXkW+MAQsCLdwqsHJwL8NkxTkjvnp3xsse8OG2aE4bKfSvCeNgEUhMjwCc0nLR2W7uEoGIxCZ3w9LahEHPLO4759bUtqTCSIv2DsdSUuIxWDAg870Iqm5KwYZH9lNBTtg+0PoYDiOFrDFTykMhNtuQ5xyBpu4afBKrDb0zN/RrPBx9/h07pHB+RTu4ImVsZk8wAq7WaOv3Ow=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
