travis:
  secure:
    BINSTAR_TOKEN: WUQkNyXQ+fNSD6tGcSM4IEAADdGGELZW8ch3Eub/ObFrIQAOX21IbpV1VlNmy4gA8ieKP2hPXI5SooBU9kRfkOf1GM0l0S8aKA5F9HObshW9BiBNyTNQHPszWYTtk9w8jykITaNCzL9d0OSWw/Y/WjEklpj7l0hQm9uIhn5Ini9CsT5EI0IiWK+DffhZ6IHWWQu9OI/XKm+akgMkPx2T3CpytBj5Y/5vZfEroGynE5DSRs3HIL4IO9QPnNMFmJCu29Z7bb0mjJkr9tEft+Bi1fnZz6FAHtVo5TCjq2BLaZmFc5Rsk/7nzwCKjCWNzfO3ePfKm4+abWi0q+nlfoIt4R/m7tGL/nypT/uTV0Xp6P6bkn8zOq8Nx4/cjajHa2FECp0CbS//fY+I1ZkGw8Pa4913l8SkCdIKqzmm12C6+2NpRAqTaKvTxhJP9tgmQpVKgHjIqRwq9RLQPY0LqpjRaPBKydy5aaKj1B5xUPkX8aUZML+ykY49U5FVr2UZqU2e2WMa4sFAqdho6M7HSjAsr6hRptp9EAfvSkom7SjergZu2VcNR2YajzxtB7Ib7YlQMiM09G/+DPWez/RhroCG3mRgQnCbDLmnXDO3Mo+CvEfwAWEFtsQ3pnf/waQgJy0ECYEXc6Xwhg4g770PUQshT5afzmZQ2iy9ypQKNThF81E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
