travis:
  secure:
    BINSTAR_TOKEN: YEibwE66pJnqx9E3LO3aYWxvOx0oxAFT3h4nty8ofkJe7nLBokxOINeHE+z7kFxS++WSfDu06PZ9esN2FXDCEjOhLrJDWG0PLfl+tAffmMJN47y4aiQbtr18mEGJIk5wmMOPTdzlj2WfwZQjQcUKtadZQtY3lBRue611U6lvydf+anwy4TWvqmm51AMB5996f5L609f2DaMsqClxv0q+6BslHIpBtb0e81xtImrU8jivvB8KZJFgvE/G6fFAUKYnluUJ5EVHg0oGGTsLMA8p10KD9QH5rOKqd40IiBNozx8tpMgmltbpO4toFjEG1yU0kaPcZjjw5jLtOubkCM3YUb1nSb9PUaVQi9/ZGUg2+19NBkN4aTnadmjoJo+BHmSs+uSXBxFCuqKxOFB5EtEqoctTYqR4dB2GdZ7Z4r+E3/CTdZxqpVBUxPPdIUZgKJDEmeLVp3237oIxR/N4WXwZtoESMk1g2t8+4AXqPqZRSMqNi0hrrpmIVAXojz1Krt2Te0wCS4gsgf9C0h8Uz31qQg1lyuOPVL4h3EHPcMCZH80NGJQ47WTLMCBo/AgwQlnnCLdMXUK/Qgzf/JMqvNVg3RWehSu9TfOWkAqKK386XJKOyQ/nY57A8NbUIoaAfZ6VPNdd0VnZAPQib+5UiHlwnGRwklACeU9yxO7cB0QWG98=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
