travis:
  secure:
    BINSTAR_TOKEN: h0FpDi7fTBYITkZhngi1GDCQExoqIVRcSXbag8RdMq/Fr9eCtosnqkZOSER3it1OVuC151wJlyhwEbv++uX6UGpiiDiOM2MxpYP5aw67HBs8Uy/lZkPgZKDwp2uL4IQBOGyFoyq5XOVZpp+EZO7oMh+qWPHhzIwhUCb73zndrSBmA66jUjQnQlF3cuSEhYZ9HarZt9uSiP/6TnbmkZxiMVhniqANWHC6H1DhjHdP0MJWuRfabiyg5tnsrnQq0BnV0KClpLNhjTnW0gbYv7MaTNh0pPiwi1H/KsP3EUvxh69W8nGJJ5VWNq3Hr1vDq0eSplZeOY9z/74ZaLwEqQDe8z4kNxj+z/BsYyZApnZLWwG3TSTYR6w9RtldNlk4DACVOryzZvxzvERuvELe/z3X6w7IpoJ4dsg6wme6G/KlEMpDw6AaJ9CyiN7CQARrj9T7GTbxCyY73fqQ/5ifSP5VHukv1x2PDjZdI49IRMF6nApa5NoVutC2qdZ7wAzBQuw8ThwWNnVZkz8v8uQvgo9fnQ2oDGCo6HWskJB1TcJaWDiUVLMghcRWnO+9Qdpn5R4yJAMJX1s6g+gS+6T2aorkwYgXzjnxzFbsl3fN5fJhqFHk6p3CGXHrySKIAsmhKwkyoj5fxvU7Q6fAW9FsUFvleEpbAQvmXlMww+f0SeEkgu8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
