travis:
  secure:
    BINSTAR_TOKEN: oCXIXBqaa1lO7oUNjVAePAhn1eygA3ncVGQOUaiei+wgCCA8fGbkHG/j9yRlwnJLwHNsxIQ5Ns6nXI9MWIRt9XJ46kI/48drHZ5Fh3snZOdfIMLTqLp3aosTF06tRPhRb2h7W0Lb+UMdfDWpZxiVKEIU+dEIQmGItTy9pzO+5tSmuVMgKcqPYNJaWVsz/N/+TVJCJAmDXVRrFZQRFOJ1lTyIFGyLhSYuoz2pXrzyifO3YeDpKFuH0TQZHugbNzpYTchcWgFp5QmrzxRXxPS8zbwoXaL5yzl7S9pPIAh1+H3huf2H43x0HcCsKSaEt4SwFsYTmgb0U+3XeFBQq/knFwzbbLcPwEp2Z40FAON+KG4ORTlv5zypqmNx1qRVuKgqyd07STg5EyRh9yKDQX+WcgiwjAd+P8ZiJOILPfhi6P2mlM+zYVqV1uQwgg+aAedqzaax7n7kRzAvdyKiJAqwUtTnUquEBWYZH9dNRlM/P9l4MUzmzyIg4SMryIN9sJJyYIt6Pl/5fHBl8owdYohncF1bVHDxsPqCrS8l7wNOWTJIDrPzCxpY4pBk0K2WeGUyVuEFOysR+NwSceK7ljEDNiwDv5MVNA21MnR3ZE6h2xIKIJ/y6t6dG8dBLaqeMW00vuqBG/3Ng+0o5KxwpfcqawcWbilKN2+kGixJnPhRLIk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
