travis:
  secure:
    BINSTAR_TOKEN: ZP3oX68tfKi2PyQXTVIGcm9CUL0W7yWpThGACBRth5R5qE7sJV5gqgUwb0oL9JtwPfpRuFWmd06NqwJPYzIe714/I2RHW3JSqe0XOHN5snRzGdznq6L/VcaaiWvA6z9eumJRajTA608Lz2dRJx5S0iext1UINyfpFbkAnkzcg2A679+09CJHPM0mP7M6gKaj80cIA0et2Y+LCtUMcU1x6ezOi4D2FA2d+o3kCHgMG7b2yUt2Vkny9ifoku7bgdc3IhzXeGgWsHi+9OQFCtEIkBcWWPnvL3uXsMBTkr762lNhnu4grsSkUtivWVgX7aMj5ijlsO6/EcEXkobdZnS9tjZLBs5XowClpnqNcEAANlFZg0rgGYdQg7T9+ZasQFUKjZb1mVQh2fpyUvSGm43VSIJ+0cyhmojDHtkw+BmdbRwQWilKzglFenrDP7x6F9M5q+Sse0eZmW2A3+xQEvKpa8niFoHbgWxCZmpGaM0k335SWESHgixvEUK3o/QoWtTraZBJb6c8czu5jXb5gbMs3YU1VazUYS/u1r6knScW0EyR3CmeouqgbtuJX/8MjfXggUMfpbPFnJ3qlTgIihMmWDjEiwt1eDUC7RjBCbFgqgya80q79z3zWxwPC9AQmuOlIHgT1v392HFi3zXWtJan25W1UURn9ZzdiV5EpcD+fAU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
