travis:
  secure:
    BINSTAR_TOKEN: r1bJ0roEep9G/L+Sc5pq3Kpwvu7OmclF7ryaET/EApEsgApMsqym1P5JOxA4I/rlbgwfjb4glywZyJuutOAXCCWWpvoo7Ronwa+rmygdRFeIvwIrb3yXuvYpMivz253SK5VhblwK/rl5Cizp3mxVNN6LCBqACym1Rr092pVFOgiKQArjxiMx8yG0/ALJ0gAnp9ngn16k24/+mpLSSj/XdYCgBS9KnYbucOkJBlv0qSP+Ke8GHOlU+wsTWyfcKGRpvo7cVcQRnvNgW8FNzDYGsiHOONXjD4m4k7KDdqVy8yhr9CSeq9dy8Ou4yi8Eg5+Y/EM/sv5scBsNCZPlcMmzx6PrNbOWj3J0WTITKBwq7M+W8KDjz1amsKgqkrnWDkCtMT46JNYcMxMxDbg4WEXwtUuPa0ZzYUTPzdfvoxdw9w098HxdJMa0OCMWtZwfyWPw9Qzt3NX5YFY+Mq+aZQWyJNEF/Pcqnz0YdbZe5uFH2R/llxPgQtut3DHnV24vh0HLE7a9GGNL7E5ZX2VdfGgSup0Hvmb6g6CPBAP0TcRG/e40dTrefl0UFpZrSKDnIHES1QvSZLL9Ad1mQfFoVZo3M+S3oOmONXXjXLzFK2G87Hg9wSIofKZxe3++Qwgaatg9X1OeJ15n1JJrqEvTSyHprN/BcPYI4isH+Ih8G2biiBk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
