travis:
  secure:
    BINSTAR_TOKEN: kp2Ul3d1hqHQgSX6htaOk6lkfmOZ32wx/Z/aFJ+AZ8XeMFKyTF2xPX/Ctu5wUnUom5CLel/d0QobIIcngBrtMQttXYYlC3pGo4A7fkvS/EGton4i/qzCX7P83TfUjks/BKTFAxbheudDAZ2168yl8WmF2yWgaFIzCf02nYHGPW0qjSoTX5mYbQdyr6YkpBWQLwnov9tUHQZ7nN977wAGB4zafjFb6GUuzz1oJrs9YxWnSY6kVjezQ2LcTqWhSIb1GFUVh8RrhGDaSLGGYIVApGhYsnNYqHcdKsniF3YHCjy3nixihMzeHlaYRNewFAiYCIqK8TwFq90QH3Wc4lNUejC0cjxB132KzkDhSqtGGi2oL7WE3waQFQEn1N+PVBkrDG0wXMItD1xk7oaxKnjyulaQBdgM0X5512L6oxlmoj777/DcO1TKJBR0KYxdEDE6qeIhKJ+UjizRHwRwS1QYNe9YSVBo6s9twLaFUW4RHpToqQsWKvXiPPrkMuP1Cc21C4B3fvgZlbK87tyTpGHGnET2ms02xsUjedz6wHpKkADnJIILNJhG7wVfITUABflHALdByZFe+TLV5sk8MFzZ43iNGhovhKxZO4PyVjCHBvXrhWBgn5p542ZpLpIDldDi+oiNrkQVwoCPYE/iTBgkz248Y0sIWCs53fM1QgMj0Ww=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
