travis:
  secure:
    BINSTAR_TOKEN: Cbc8mQWT+3DRNDEf4u7ywdgXtSd+g1gPHndT/pGUnYf5jL6mHApez6nmy9miKEGhvbZtAMhM+2vt22zSYGzvNyey5hfGnpuIgNKiIKVr8v8UKgugi8EawgkdU181UxN6KySbEi9bY5jv5js64+6ZnJgOB8GMkRFRtXf4ciVWYhOXE1fCitbKM1KLf579bubVTwv1JNhnFf5d04rsTiJ8V0E18vPP7MzQIqCfCO8D7EBPcuALpYlhoovbrKdYYdbb1DpNxCo3mFytzo45OR6rxNMDEMkGYc+vlm9aduUh22qmNyKPUZ57G27T8h6pUlHW7bEwiJlp1+6lq4AB8QYFxzllIa81IwMHNyREa3wBN2wp4H2lpQj6YTssZqnomWE/CdK13RDu2m7ekrpHtc4+euzHTZbi3cDTtUNhFPkjUOI0d6MYAJ+q0Gi6IaTTc7qcw2eEic9ukjIyIkChnFf2tr037IILqlIXtfKOqtzXWMxVrKaqARFB03M7NgBL/urbR3BEuJ/STGGclh3OWE/owSCXJgPvDeG/SabtRg8Rievjpr/strtR0xDcCmDioNESubouejNJTEQQpI+jaG9803oSH8MJLkPO3nwZw2/xTaZSG3pQTYv8LiyOVdDgbxdme8JWwOga/9dAW0aiSkx7jfAp92YHblTKQ0fQAW+cRTc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
