travis:
  secure:
    BINSTAR_TOKEN: dFJC2FTHaKONwZSndgTDOg+o0w8FlB+86XKYCBAzNQ6yAZIX4bgHI6JfUnygp2/u+i0tVtRcQaCLSyKgmUeHfZwoStu9TikGcNDI1Hd+aJOAvAz8hG94kliGlzIwLvwgEwo60rzMHorlm7SiZ6oXDu+3bq74/DG05xjBYr/IH/1pvbJ/GontN16PKDZGGcrdljj6wiGPvjilfQrCFoiT7R/YqXyCMCmTGQnulhTJ9KEI9/lOnWxGrSx6CAq0czWnGpjKfc0mslkPXXL3xUDwhooUWxR6rOHP5ACB2dPmmBj9+whaY+fPK6F6fL9xR4Yrk/ZWdNv2p2neRUzGFg9da8k0+E120sb+GVcU3vIs1SSNB6bsURnFK+UHnsj7SRlVfNGsaJUA1JbnQUqpTuz2MGT6NgAaH81JXLEzUWUHBXij+d2pdK5LzZcAEzRTipH+KCdsOm+0TOTE0ajj2uihGMkWGmu/BgdHYz/PuYgk07lfTy8UqdftIQ4mAOroQVs3vn+siycHXh8ZiEkvjJctZCIfZD3wutlgGoWiOFqLb/zypNFlR4/fZ/AA+Sh21oNZYj1R1MzbGZaydhtqRsabpntu1/JzJ+ctVKC3YDsVwOXdwu0DLIMRKY/iAYyvvkza5NI/eEiJftU1WQH2qHMjOiXaKxSj1Z3hIDTrSRGGHi8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
