travis:
  secure:
    BINSTAR_TOKEN: Mbh8jU3wrb0D/vsBp6rG9iAQdNsJ1Z3Ea6CFml+h9cqA63+8bS9cm6tRFvpj2df7rrmzmGniKyqGzFnP0ALPBWhnj2/1grbL81rfVwsXVEbg8Qhduv+Y1Q69Y5ppgZj3lb3G2NEMvKkEBNdFxaASPcn7PjZlLv4+jywxN2K19ncz5H2rlKujuvofZvUFhib7k+UdWM7DoTpjSnzvN2Al6f9dGBPpzt9BLqs+5rewze29NmLE+5789Wu9KuXa5Db74rX2/0uIjOzhytJlWWys5d+NunR4qsVgPwc5TI0cse0CuDqfAp87dj+hRzxCDDUE2/Dwo71kmIaHJRfQtJyD/je398JKqMQTciaGhG0F+lzNdZLRwowdIgf0fx9KdtBDhGKshv9BWJNkdz3gU/OZhRYoGBhVayhXociZacRUFayR/xZm3voNW2lUe6AFvm9AI5T6IJ6yqZOduxQelZrM36eeW1OgPx8ZDQqy1N3Jj4G4sNk9ptu7/Xq7LT95VJlj7KJJc3vq3aWnQ3ef0C34SvXHSLyfHv9vW5dcVXzVPtqTm0lflwVB8XkdlGtTFRgEUDJ0F06g13KiIlrWrM6V7YetE1vDN9lZ1t8YQvYwwfF4fFEBronzogI9i2POyqVwz3t3B+vAF+uERLu7Lo6Epr9/3ArmLbmnNG+fbXDwBN8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
