travis:
  secure:
    BINSTAR_TOKEN: tuhm5d6mxtIHerKSpaE5gOMEdEBjOQo2bsTPuz9Es1dXuCw/6tJtVvpWzeKCZQnlTzWXRdnCnfjgv2Xi4XgLiGR0S57aszd6HyNbhs2z0yi+CfiEvx7GUrCVoCl2dUE89F5ltdJohqhCMzlWcSg7BFhFDdlt/5vLN1Au7M5BaIl+TLJtJJBI5hAgnkUfdwddDy3MU8HvODLKIN0LLSwx8m2He4MlsWyvxDjJCIk2GiVm9+G2oGzG0JWNblO0ZYENAcHSwgRpvVXW/cSJXXK0Q37qmWKFJ5WECXztw6RfmUhJnkZuPH+sGqcF5ec209zdOKerMLTTreRk55a1OZZd4rHZ4WjAZWbKkEOjlTZVOhgpO58E7uWMhJ67yZ99Nzo+COPRsltTMly2A3cMZZ6Lqup4coOqydMO/Vf1ZpykGtO6z+ceomQvbjMZOGVCNRFj9Jwb/glHZedmyORe8tx1pYHf6RKA8zY398qjpyHglA0LpPvTT7geu9PGfu18GEsmr+KFszx1fKFdjDOOIJyvUa1dFZ5WeXUSjTXOcDh9vBqX6eOuLoS6bAW/lNbotcw8ypKnHVdfkW1wh2tRFkPO5BbwodbnE6V1lck4dadHUdNtkJMheNigTbeOGT8UlW94BUBVgs1ejQIzx/RxL4qAB6FpSfUrGsVlSR3mmHRuZ4E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
