travis:
  secure:
    BINSTAR_TOKEN: W5j1M8ypIQJh/dJ2HqmY8SGJ7Hir4LjFrFyw71HfJ32rsHbocUuZMx7vZXnwL7Y4aE/PPiwmJgCI87qzdHvVYhpiD+GLKJ0Xez02enyurJ3NK4PX1m3p9+bqvn9dt2g01WGfIqcKepBacWEeZY9dKVWD5tDvT5KdMJKIsbanoSIH5580TUFUxMhVYuOGZcn4HunkzB/VQrMW7HQ9cp/N6nBZv3hoUk1xJwyTLExsRYoY6JQ/HPVWdUMeBwBXA+jGAOMKHJb9+0unHf6IHKqkLg4tmoyT9DYqRghPDoXbGkPWwdswPxmoYQk45ViFWFVODly543MVUdVZ/A6gzXTaG9TE80nfKqJqVTDYfwTSFHRKjgFEsW0d+K3a1kgV6j191dLkCWVZoFK1SgHxX3yjoaRS78Ay7cV1CTb3TQStb+I2EUral+NLyZ1b/T/J9pqH0VxUgOyPs9pD3Av0Ly1MBe6eg+xgW/+XWzwZFzwYihl7SPByunBFkggQHXHN3wpV+9lNk34MBV7mrgtONoDWxkKMB1YP1wKDJFAoxlNj5Oe4Tewyy9PoU6YOXt9xJyO2+vh6/0K+1pPHBLNHCGlKMFYJHjyZyiF3ry1uS+xgZeRJetb0mIm0uPtbmKuPEvy1mWSdXWMjiL49GtP8gP+lBkD7sohi3gKPy3l9rC09C1M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
