travis:
  secure:
    BINSTAR_TOKEN: oaknbUZabzHhHAQbF6oc1MJHmXW8UPPEBypNJJgs50HPDShiV/w5WdFQhEkpTYNUEX8yBoFGxObm4GFvT/dKxPECf+iEJaDSvbl17SKUu4RhtiP+NCrMYxXm4X38YaIZUFkykgy301egcU6vD99BR18IFr+fk4q8It9/9RBfL4l7WfBlgA03XxFgB0EVrHVXl0hfnEipuq2V4nTLqUH6uhmwQYPofTCgNoiu+CjMxhLf/eX8WeYImjleyQKOR6fIlFCkb9laehPcTgiJwycADrDNxL6xeMisoFHLI1gj76HWrgCrHHcWhAPuYoIoXUSpG5IxcuZfLelnqHHvJkro3cFjRWLkdIxIiJ2o7l4XrHXsAU9e/5hw+rpADARMPECJKFBR32i2ZkAaus0ad7yRVC3LsC3GSqN6/cC0i0Jc3y7WSbwa1P73mnQQDZ0QJAxMyHBTBVaJ4GvGNC9KHAoRshmes8Gn6Era+ZvabOm0nayy8WcJmmTQh3PM1r+V7CSF2GEW7pt84FVcUV0jXXg7AAuLnDcNTda3ToLhxMRGMxmKJwdKs25QW2sUC+eL3RsnkBHFeCRHgXCTlPyazAYVcBMao+PfxQF+3MYlfAKqlZXYQJEFDeeni4KIaGCwROgDv4R5J3STqASRJzkKYB2L3WaBLpwkp2SH189lQ80ptzo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
