travis:
  secure:
    BINSTAR_TOKEN: FhzZfkQOuw9+5wk+ZR7kxtHAcGFVQr+3CCD0IcyelERhryMtxGu2NDpPx5LkdyW8Gdj+v8/oXUIIju3kpKX4cdPYrnkPQH+A6rT0OWCwRYKeu+OSsL4L/vEVTnovPH9DCmq2LzvqUT1KKqLRkBUltjE1Z5NR+B9KHAHGjst5CoA73ZVvJ94ncTJXn2taOe1uo8H2GSMHQoa9xCVzTpu8HloiiYVJwg8CJ8ENxrWnlc4y0zstHiIrfj9wZnaZqKWNJ15a3lH4u9Dv8CQDWvm7/SPbdRbqF1n4iQfDEy4I7I2b/ImiiI4w2A1fiXmUN+7bMKwSPOBJRR3xaVasj+8kf+W9aK265T31fLBdFXn5wHU6pvG3TiRXgneiyZkBiHDkKygHRWRNUEUe2u4Fa5reAniJxXWXz/wPdDy/D2DYtws5Oga5w3ePtjVk5fj2I2RJFePCDNaBfxaydz7Z2uixDXMeMbF2IW9roPpiqz4DcKf/EJ9gWFxZX4ZRRFkPXDOR2WUT0xiTEjPkw0uhvA4DEykvJKnDxmuCH+NRg034QGax3DQ5iSw0YVMJLmjOqUsbWfDTNk8RjDRVXbGT/LmuQlwpX97Lwtwl+2/nAz1gHCTJyoKMEIPgMiJ6wYP8MmESBbH74reDQhZJl880rtnQvoD3q1YvyZNF90dsOyxRwZ0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
