travis:
  secure:
    BINSTAR_TOKEN: K/xiKzmrcRMvoNgsuUnf1T5AKHcAPxT4Fxxw2UPEomYsVzjtHQja+HXK4lgyL+txJ6uH0jbeoc13aVo96lCFHXwiIQdhRcnZwEjSR+rG2E/xDC/p33fhW0880uf98KEakPNvVxrf1FTRcqgysDroHb595BszREeG8bKjDihi166R2codyr/p1wre/1Zx5WwfoFqKkopgbWyIi0uFj4biMLu1Qvy2H+iG+4U3UHRAGfAuhrYzEVHmNvuQOEZSEJZ04jEmHeEJ8M6cb5YY+VqEwAkw4mMWj8d3XFfEWNlWQoCO7oZuvQFElSOZgZNn3VpGs6GMLm7PziJCzktR7sfWJHlLGlCn6DTdr+yWx14m4mKxUMsLv98Pgl4i4w/pVNH5/G7PWnJeTHmFG7CxF44C4iebjuVGOev5NWe8a7f8Y9gxiPz/Z6zXvdGOozQ9Oyi+DIgczCkGVN6VN5ErHi7fsB5yXo5BLEHtVRRfIvwRJslN2GnbVYY/Dc9NPg9+SumGMkvIz2cOTbT+f8+Zeglggg9tDuhZZ6RqafhqaSknmpqCfbcTlJalQK62bkntuZPg74VX6LmdMPoCbUPKJjxXafFk3nAZxe2mipxvm5kosRXVSZIh0qhbPjenvUvnIuzMfuqUtdquHOKCfUJpmurP5nKTXk+EBi2ZIYR98VFpXgI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
