travis:
  secure:
    BINSTAR_TOKEN: fQu0PKeY41yTu/gFdiUmfmZYFZt/5gRkM8PqY48ngtfZIFX/KFph9vKCxHAg3pa4NECyf/8KTvC3hfA1RL5oCfsDgQDz3WF9sYmQmqfEW8FV5xVImv6wnb9y1HhI/VfRvWT32vs1s70ClbGSGvQ5guMcnDvjw/AVn0whtUfbTBkZJrqsRys/GSW1d4jn94ao8oRJ3lat58WmP/pc6j4NdfJCU10cT6BzYJ2wkB/S8qxT4jEB2sjDkMOmoAJSDAc6yqjE8r+RIif+0jjXZjIr0IxG9tInDNO9/ECww7vkR6SRN7jstV4fQBI0x2NLfS4yLZRvjDJyTF14Jh8sNHbGYBK7pZgJ89JktKTy2Pu4/GylLpL39O++/u9++k2REvJVCZtFVp6B+2JCXDFhXp55fx7ozh+U8ORx/jsq3MKH2BDLSzx0jN14MGoxTPU+0d5rcf/tOB+/CSI6NjkafNev7TRfbybRpDQDaWeF6UN7gf0BANmPMuj+YodNh4bqeueorxxAZMLHaKfy/oetRxlZl0okHnqWCrv2b6eUAM8hO92IbL2+knAMCgW/2aGOV9D2D7YYQVeTG5Ojy4Idn1DqED5z8bXmMWnlCXNDe+05NYgg+8IoRELoKaIQTyCf4eU7DaTC8UYw2/EMVpSo0xGkQkWN+sJc53/PWoD1XSDhzRs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
