travis:
  secure:
    BINSTAR_TOKEN: Ira1sVnJHXfjdigiliVqCkWL3moIfKyKUHgKZ1UeGRsTUTT899Q9xEHIR7CEqj/m5ZPrEDMBxwRRXGJDlKRnr++158FqB/aV3fuTbDSs47tNwPhqXMDGBJvaPcHVeyJikbiqhm4+aRDytlBG5l8lmFOZdrDdMz9MfzhwA5Z2eJPIQ4c89F/JojpjNkmP6NgFUHtzZ1DgUffGynPtRyKMTMSvSrCDky6RulX1Rh4LNtey6Hj6O3Gy/z3JrbBN9KnLqy3RbSUTJ0KeXO8bSJMCPG0zmUNiwZ2MM31gaqeeB+3t0wcWgPMLW4WgxMDUehHbvZNlGhpufvnQMveADKnpGbsQdwWmZYAskKkEC9tNgwKlbWnxfG6GDE0PRbH0g7VyIZHxnEk1/bkyZkB83OiS+HqVwOXANC44kqbzfQ9AoYW6C9xedhEvDGpG+eVphPu0IqAKcuTh1BsGq7maBavGoZtIjMWkG2Ho5tDCjopZL7CIkg0mDG7Ozh8IH0EolLTxQfbwxUX7GgB1Ii14QTxBIS5Xev/xght94e5S80/dBgoyiZcgl/4gxlddKaMBeBtWQbblqU27URZVcT/xOLFv7WlC/7T+3C/seqHnTTXVsZFeKv6NFa2HZXK67S8vMvgbUuzA/2OdnjfIGw0kCvMi62NlAAOWIKibFwg5rLMByDo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
