travis:
  secure:
    BINSTAR_TOKEN: XoEWkTuJY9Z7swwCnrWe4cXgUkmAL79oZzW4P28mfdttYnGdz/jFHYgQDJ6N6TByVGHsMOdTaAgrFGq6gyQFdQGelHok/4xtAasjyStlcMG5dB9ys7Kz1GCwIVyO03GW/EILOOSS8GdRSDKwi+HZXD6NKHUFsfR8hbPJmr/wPMZFCjb5EOhFspf8JFQRUgQAisT8vEOmLC3ZPkTYJMTxzY70ywO5MClnIJd+XWV/RrPK2B42Od3GvSeDs3IosnHEhUuOToXW/WhhDDjoukNRy3zYVFWaD0O25vsyUEXLkJWYCGX27maSYo9VNE5FPGsPNeeSl92Y7GTglqZRkznOHSBUrGV+4BB+o3glWgLcUG2lkcfWR5nwN/u41ovTs10W3pqb6qGUAJ0HQ/dUNKyTegNOX8dNy48Zm5VEKlmnMUZQpuV3Xb0LkfwO7JGaIHImBnl7dpxPEu1YPUTtGTPemLWK2f8+Q2pwhHwlE5F9FkjfJ9pidVLs/20thNIpw+kXcIh9ySXfaUlnhL8fdHk42IfyPccSdtU9VriBfjaWIpLRr2uDnp/01FosnT+eKVMQtTrKOWouQBqhRUHAaHMOvd874hR/rlgU5qDHGxLtEQ/g3HtyZL0FT9nky79myWnOqCXgsXcIvhkECROnj8fZmd11zBcIxEtAf31F0/N65+c=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
