travis:
  secure:
    BINSTAR_TOKEN: SrE1//x4mdsIgFqj57KBToanwV0rFZj/Df0bhUktXabp3yQlN+hAthmXuL0odThi7PhRaGx2/MUqpnLUAY5GHpRpf+R0BMkgmDKP1lruRfzJjCuWERtlIojtRAydAeV7YbJFsedK8aW33usU41D5v2rnSV/pXhY5IAjO+29INWhCUG8HHT7qq6GFuxz8a8syb4X7KAYeOvyse1YGhxtvY3vQ45cxgjJK5f3uNI9JVeDidC2eNX0wpaau+QDwgadrUHdR3ekQ0m/tCOFCX55aobG/lI4pkkjjcIv3nVjeAzfmqhiypvfIgL8QvODIbaEB+sq56mp8x/cIoZnjuGKeqMC7LlwOtcXfGeFoP0WMb6tKxQHa2B4n8E9U7QxSzQVXmgAk5Z6qDiQ44+R+8t+QhTJkm1uSV++4h7EPSEC5qXcKg9Ym23BfKNySlUwwLg1OrTJhV5zQb0B386fnN/duhZPkie/FUCkivIS8IJDtKFR9oXlkmJMJy4+pe6txZKnyHjrPp+rCW4EwmxqnqXoAyxPSdOvOAdMd1npiaL+GFW/CHnzIli7KxcV7OMNuoCOmcCz1dvTXbn3xrbqATviY1b0UkDB5IqjtThAOxgIITADybKQqS3W8a3vtheIuvglVa1HSPJtBw3/DdfjbPfIUpiNB+8xZrAb0YBFctcb+deA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
