travis:
  secure:
    BINSTAR_TOKEN: TwIWtONZ9Ncaacn7g5BudgDedZyPi5WEtq7adcfvVIImZbCzxIDMIL7ZBeAIkxGQJ5xBeZvlnRtrjcrY5Tcpp5vvemwmQXgcBMx7v/yI4T41Vym7woi3uYJg7+tSMEJEhvzNDQmfx2VrnahtCD3r76PTQvON5rPuAEQQL09nvW3x4c/9miimpP1iH32cjHDO/w1/RuOgqCB/D90KGz89kz1KCQNQfa6Zs7UniEjmZBIGPs6LRfQY2rm/OJuuMgjmAgN9ZVXCK9DY/Qvuu/z7Djq2+E+r8c5uAfjCOyGswMTu4tOYbU9P/oUNaaRkXQIUkqxqBOCutRjCzTHbtIG0YlG8qaWEixSK3WPQN8ke6pxs01oB6p54PvcLp1qeb63nTwyXJcGqYEDooj5gSDdgfwo/fF/FMKlA4iXJ/Ps8+1XAq8N6k/2Y/m37IeGHb22c+SmVaTUfVtw79Yl83Or9jCyq7/WdnRFKyVPpAJryYt1NSUTUr9ELh8uSY0sibxB/UwoP8ctY/OSpL8bcuz39mlEFkz1vlghyqQEiCHYCOg/mRj3aOXhi4TOrYdkl0JzTpy2td2NGUt4gcIDVzsog7z1I7tqe+OoCdoM9ulc5rrBRQn9GkPmjdCRu4AaNPidF61TSomOLM1Fim2F2fbOR85HeflbCj4Cg7/MQfBLO29I=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
