travis:
  secure:
    BINSTAR_TOKEN: jmRBtNfexOMPbc7osKimw7G1mvLR+9aJFDOuMooNtCf5f8JVrgoRAuGJr8Q4qGyz23r76TTQEY9AMSq6/xj6334UejbL8AvoFfEIJGIn+B0LJVYQzIzbX1FRVFKBzHahRRi3LcCNODG5YznjVyNHagsEqfavw59dX5P55yDmkwMGw+iTe1GTNGC8e5End+qvSVGzlVOx4fUqmeHs2uIcmtHrAGMnBteGBjcVFPspotQ3iu/IBh1/3WzHdNKG1o+WWZlsY/dbcVM6TTFApq3CFcniJlrVUfCKVT/KXC1eRnuX/Mn5icwfbRvHmYI3T3z6j/MP+ikpmvRGbr2r6gMN0XitBr8TlYQ563n3vUhYj01wH+450+Fvez1RNpx4An1lIyEMetWfocFZSl2NeTBDFZyIi+WRdjwR8NfnoE0IXvyRZYIAOlPkQVsbZCZ7ydhc4cfSUj2ayV8EvjqY6Yj0mparscXKNtbLeW2xIKFp+ZawYO8TocyHThRBIhbiilAheYS3bVSq7xrjvLlB9XMWb917y1CYp8jUzzVyv1QhVR7Ka0mjAhq7ZDQjznP6pUst7DCfI/mmx+qGsZaUZ+mIiJHfdCo0AiG4UOqjxlSGauusDc7WNyocoAXkDFzFNOny8a3oCQfajJ6tnQpdq2Vay+ypNeXqvqdBRQWyPxvQJNE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
