travis:
  secure:
    BINSTAR_TOKEN: koDp2GzZeFjFjr3t6SrZLh2qTz3d66nwcPEPbek0dbN69QPs0Xmq5NeUuqEOv8Z0MMxnVm5tYP8YVFMX2sKTM2gvZgQ06yKKaafQFab2RNBg7nykRgncLrC+3bOe73bBWrI8tQRPr+9VIqmZfPclc6HzW24GlONLtMCtILuBvbGaL1SYnr4i3CnI/dBQfr7PaTAlhkoAjWG6AXPH8osPUyTdIOdc1ytvFFcppCHO0CdCWabQ7kRznwqkZpw47pzbGNy+8nLV2+X2O1IibXtpLiSNapNkcV4MdCsyZOwqlxY9EeC7e74tpTHXKxfk8WPmnCcEONJ4qlGF/xEWen0mgm72y/hNRq+AGkSUHRG6pFI9jbyXIHG4XstDL4v0mypsI31dPCS6viFKvfxsNc8TFKOaUrMfqJNqGBm+83AFapzsqiDdye7wjjpz/iNp8Spdkq8asOvz9ywKnqQTplsngujQcimdgLwokrL8GhSUxJpakh2j5RSU7/tgUEyoU1s2IptQTQ/fK0kJVKM28WVG6sZzpOAYXRs7zsLQvC9jqvts4zFTCA2I1BzttM0Wt4gK7vWPdvhWu0Ea5TCePPe6T2O+LysdezvsMSmul2Jm7MQhgyFcVinSCgEBxhB0CBCUeES6vrJU2m5TR1cSqAbedj9GjJ9fujkx5KoX0uO+zO0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
