travis:
  secure:
    BINSTAR_TOKEN: CXG+KIDOZLk2+DKkHgp04z/M11qPyPL5Px9NAEQcTTwSsf7bvbAlZpJVacJ1x0cUQ5MKiHtM/QnoWl0y27+GjZvwhyTw95uuoyh3l/l3BtHhaJQh8NlGYtZYcbx3f2zl98Wc2VqMFtLSXbE+bHXLwbvf0lcQbiDZPZM9igRkjkRYST8od1oO9nM7wr3fU6YMtIDGK0yHc9qi/tuTMJW+bI1NypK0ACFIwyN7HU9bcbC9KuYxgjfdf8ENvHwySD/GoNDPLqUit3yluKhOqNxkNpbUKRm0XH/HpleCT3bJkk9uAUcyC5g7H1DfYpYslI+Xl37Q5MbrsDP6EPI1OrAslfoVrDv+39K2aqtsWY3MWRKz4aT83a8aiA39l+/+BMzO0QYxLKFra1TC/gkLZZyYZXJ2pxTd6VkqJg+Tfx1/pfqLjwSFvNfXgii1PrLKQtiDgV4OQWbGOFYdf0L0A4IRMMrjZr+JmaGaeIpLKsH1mcRIhumwdWbiDuHnW+79rJBDFd6j4vuKTE7XiJc7WKlC1qhp1DBpjZBA4bjxU7g91CYvcgRo2w9m7WQdQkPf8Q5NLw6RJCAAiL1KeFl5WY06Z2KLTjno+/1NlTcqf2FGTMjyUY4X1diCPDnv5+PWJln/aqga+gIKkRgqfgNRSL5N+4CmToAMaIVku1P4DR82r1E=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
