travis:
  secure:
    BINSTAR_TOKEN: pbz2Uoz9hlWelAcUntzGl0KO6tjibOup/aV13SUwTwXdDPG0oVUybaSJBaYU7GOQ8bc8zFvZuqVosHERK9JPGRGXKDjElaufcUxUspjlKibrSUvZmrX0tZignUNuFoXVz+0CAhEY9/ovTnZXuGq37CWGG4EiPELmjyxdSygQQB1m2rwCJu7g5KoJMY7uKTDaTsPFSNIubHJJLjOAExN9W+QLhNly61tOx1eSDqxfHn3Rra1rFwPDKFuL4wvjteOfwlBDxfbAjL9sz9P7DwS9xdCeVgp6wxcrZpGcU0+7hzn2wQhLgxT+czDLTUQS1SCd7wAR82BK2Gk60aLpHBBzft9g9SuDcXezeZCcaDDTcFZpH9HyfMiQZnNrYPoxtulFaxl33xiN2bKAF+GdGhXyrnFBYE7geA+wmXSpswQR9LURo7+yOb/BwYwXtSb2ja9vDNPwC4KIuECdPZUMtHlSQOdSGeloEniPa4MsGaBaL1TpNjOYV8xXBqSDWx0huTxtCOW65wZPtlq9DPTi/zFLN1qgQaYuF1t2Ck5QocAanGdRUE+50v0b10/ljzHDzfLSkzMDxbAmhBpLDlXUVqa3z+2q4KVL7TuH0Ata+3VS5tJcc6ZKZr5oP47GCi38B2BmAb9G1KvVBnMFTKr3XI7ZGCYZbSYEibPx7YX6RhQIMoM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
