# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "p17r7oSxHvQYqnOu3aG2YaU/K1Y26c+cz2TyqqEwiWQcZKO2EALlziU630RsTF5o5i8n5c0MVEqaAGzE12a9p6F+sxhfrHMHfCHqmep4mO3GmUHmETTf+O3Uon1AZLb0TQaVEOIvMv+F42SeGdhHS+p1hO8+qpRWHGFImO/J0HebmgEA2DGKW8gfiSbURrLuP0jkH6nTCHlh+ntm024fbnsRXoNG7weCC68Yw6Wrj6P3N98zvC0RMVu7oZUD80AwXDsQpGIg2q4DUPBSpTpQI2Y5YD6IBBR2c7Q4G/Erpy9K2KVtFhv1lR6LbP48kc9BpoMchPBEPHnzl494Sm/cbnUwpr+5mo8QAJ5VLagC9LvVMLLwzQA3UdORNGtnd0RHNj1NcjZPlAjkdmEh3c3DvtcI8WvyN6gvIypBMw3Ey/ZVK8LteqiRZgEErm8iL8Gue7S82BYVkBPeP4cWXnEq+eGjHPhel6KaelAfepIgPV4/9C5oEOlOfoGDUiEPT2RUQCOUEA6Lo1CJBWiJSw8WOHJNDaY9xWT5Ii592Tff85VrfLPzqP3XUUZmmCrzM0vSDpafoQCMrDvkTCGi5sDDaogF86s8HqjorvW6q5yZU3EkkgTQ5EvyPvB7iLFbOoV6GtrR5xs44ZgpxyD9aQmu5GVvxS8dV7jNdkmdu86gUoQ="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
