travis:
  secure:
    BINSTAR_TOKEN: p17r7oSxHvQYqnOu3aG2YaU/K1Y26c+cz2TyqqEwiWQcZKO2EALlziU630RsTF5o5i8n5c0MVEqaAGzE12a9p6F+sxhfrHMHfCHqmep4mO3GmUHmETTf+O3Uon1AZLb0TQaVEOIvMv+F42SeGdhHS+p1hO8+qpRWHGFImO/J0HebmgEA2DGKW8gfiSbURrLuP0jkH6nTCHlh+ntm024fbnsRXoNG7weCC68Yw6Wrj6P3N98zvC0RMVu7oZUD80AwXDsQpGIg2q4DUPBSpTpQI2Y5YD6IBBR2c7Q4G/Erpy9K2KVtFhv1lR6LbP48kc9BpoMchPBEPHnzl494Sm/cbnUwpr+5mo8QAJ5VLagC9LvVMLLwzQA3UdORNGtnd0RHNj1NcjZPlAjkdmEh3c3DvtcI8WvyN6gvIypBMw3Ey/ZVK8LteqiRZgEErm8iL8Gue7S82BYVkBPeP4cWXnEq+eGjHPhel6KaelAfepIgPV4/9C5oEOlOfoGDUiEPT2RUQCOUEA6Lo1CJBWiJSw8WOHJNDaY9xWT5Ii592Tff85VrfLPzqP3XUUZmmCrzM0vSDpafoQCMrDvkTCGi5sDDaogF86s8HqjorvW6q5yZU3EkkgTQ5EvyPvB7iLFbOoV6GtrR5xs44ZgpxyD9aQmu5GVvxS8dV7jNdkmdu86gUoQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
