travis:
  secure:
    BINSTAR_TOKEN: QcUuOZdk9eHOoIKsobLNCrsNxIroDey0SfjgeDVP/kS7jtDt5x/TYU8oDz6aqXlTCGsQC2FMQLzxxOzRtJemK21x15Ha+mXUzYqQQ+7sRRHNcnzEBehPak6U+9D0yzwop55efP+HBXYsiydqDxii8x8EOMMMKlvo35/EYqZ2YLZ37NU295G8mxYCEQ/SC9WrJL2spPDw+6/VeSV1e8ezaPfDEtiqDMeqJtUboqlt2nsg9MMomN9MlboXO40R3e5rxRdwPRXQePiX1CcJFySik5flUeXML0m0YpBvVhh8OQqHY3fYNdXZCrahvYHpC54/ScnEL8g5hkBIDbuBujtKsiL/Y7ErguuXsHgwCD032/Ql3o1I3b1CQYTA0VPdHYIsarUHGDSclD2fglnPS2N1RHp/r2Pjh9GmXHCHNZHY991rngtiwm0nousfFVpj8X7VT6g8MF2pxgq+SpcSjcvZQakkDhqicULeBLEBC6NfWeZu+cb/JEh/EniWItbZGZAHm744thZkN1K9k3LUo3RSi8P2SzSH7ds6PbaQ3yNO7hJW9r1hkoKCC5JUh+XGA+hccJUXubAwKLZe6vvfB+GxLE3dgre/9tPqGMb9iOBBgHxmN4Q/oQegqY0xN8OXwz64yqvME2D7N9Y4tU89kE0Q3O5/ElTglJFRo96FTbndXNc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
