travis:
  secure:
    BINSTAR_TOKEN: qPicBpGpHy/JFhoyP4pjcaaOk9/4cddoRBRbR7eXhJOCiqg5pKMv0J8bYtc0bmk5hKkLRrQLlHSHGWC2BRNKgqc93+i1rtQ6+cghvmO5xxfVT25bHnpY0GpmyY8/dVUrVdSfc6cwYXXjoeAHmQS4WqsziNS+ZX5vTrKbd9c60FPb6jubUoD+C9lrPAsedfHOD1k4Zqa6lP49nPaJiRHP/DEczj+n1gRQjPlGEM5zlvucr9Vt9AC9xkvykzsKky5NF57CtAc77pUWgoyIKaCaNHAx8bOTykUGhmVnuyguyxmwkxb3MJmsn5GOYEV4/NlqIi/Exhe/kmWeSY6v8l53NGCMJmhyxzDBvr603Ty/TrN5E7z++anupEbKD88TuYGABjiy04zzl/l6F+fGNH2g5+ONydTRSy9699XVxaJcTRlMPhGcF5zHfdAmuG8hI0MARO5X/R5aAEV4CZxcGMY0mEglQzkoHmSgWfn7bk874zPGMP07Il5JXLQS0K/qiKIr5Ww7pOR1UyiB+0zepwn0GM6hujOcEYS1GkIehFA9Z1KmHcmlL4eQmQBc7EAGKHynOiAeDNDQ2nuUHTIS9sqDsaVy5sJ0R7m8QLFpbaMy3H+nTDRidrEqQ/MM8WQEXMkfh0EmZtmKlXcmsX2Zrx9oK9CeH8dI4CZJguyfb8+jNn0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
