travis:
  secure:
    BINSTAR_TOKEN: b+z57ONvCi9iuCeuUJX38x04fqG/4evITpYZKvsDhu4OgpPFRvUylZf2J0uIDjfKYqqkPpR9TXLTVwBMP0+PQ4q/U1QpIz7Ys+ElElN2KCpvkeer5k8+RSSiCNH+U0VVAUl5l5VkrtC7VVNhw6GW114N0jH+4z7Qw/2cv6m2yFuRf0PRCKu/IIyvMMgMVRYVBrkvAF0SkLL5NUBxXPnDuN39Uzpq6A0G8IqSbuNvPnRwDQ+LtTE4aoiAAAgZ+tztz3tqcG1isKRPJablE7jgoRwj09YPZMJDfV2+RgOliyJbaq/ndyh7qK62QLdeC7xZ/Xmfo2pJc6LqH9xaqZ4WVoxHPg9Cq4+KHuaZPR3r5jO57ino2VFDxk0awmqtKHht319QEd5sbDi+onfo5NnbC5NYt/nzu//kY9+pbve9eZFFILLuasKcrQ0HfV0LMjteW08CBWSBJoPTbC6pI7TIeDt0Cs+G7wwsDOpBlDnSKFMTnYJYS1tyTtJ7dBP8+yNq0Dkww6AXVciyRYOpzrSH5UieuASxhENelPq5oFbJJnmtREqSaCwG50X9IAkZCUXCuOJ+id1RaoGMfZ2mfUwjwfndQyNObWI4iELjeh09HFaue0DC6x2qeV4r2t9tiddHwsWLGL5vtNSfKc+LUH81qEDVbHVhRrqNQBKcy6ay22s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
