travis:
  secure:
    BINSTAR_TOKEN: f98TaG8ozne4X98OdXY4SXoGOzaQfBGkOv+REHB5MCJ0rIsmRM7bOh+Igdmm1jN4/HxHiPPycIB2suUNn8sR/25UWp596SD/Vue+VPLC+97NzpGOi5dQcol0owaErzUwLgHgo2s3fX43im8Ic3c6t/1Q0AnwuKPROu3rmQjqy3m3XYfky7aPtNmmGt492ZjNJXKnkn6+xPS5o5e6FI6IIDjfsJ7z5AJzANhmVrx9a2Oo/ocW+3msd0L87MVkrKCd/0SovxSRGZgb4IxJITLAi4CwhHeqf3wip/nh8vQbAV9UuJ9mruQ5k0q1PgM+c2rxMDhqr7yUiUFKW8Llv1hFslAZzswMNZgT48lCaGH7JNp/IgfUVgC1KLkHN9tFN0LcTJXmU0EFqJ/VYkOZUZbdTNYvxCuvyc4So0u5MZdXLm7B5LiM2dXvOoyZUqW+URwDaD1b+xdOeIpDGeunQGSP8bGu6piCcom0iAuI+Clux58NcgeWuDFbMWiaGJEfzEQ8EN1NghXo9ZXr84dvKxSur0g72vo/Fpa64Zvl6Z8RXFvxdCqBiyE8uGForYMfsfGkvCvDF9QHCuesHHdS+HR47hDVxdThJLmADpqE/vxUHSCwCjYaiOSBnf3HpVKl177t8YITDdbDP6UQOy68B+zAW7G87y8mmvqDN7s19cbtfhY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
