travis:
  secure:
    BINSTAR_TOKEN: O+0lA/1uUBGvz92JOTebLWAkaG0vi8rLqxUNDREtpfjGKq8jboZnwpR+jpL1W5p6s3EyvCoKGJTT6xf6bOynHQnrbCHRfjHYgZU1P29xMqn0fQCWV+rAoty+Ugv8dWE9uBRhcdX1QZrYry0fVq60gf5zHn/suyWufegekHwoN6mbkN9/Z52lxi8qF+0buZKfjiFh65jpA2cEDyWZUyU7YCzdbwwenZnFiJGsD1gL2nU1BDlH7mSkknGKFtgBAnvynolOl8ZjB1OAQBHqvNVrBmDg4V69HAxri7fiBBUxQaKwnV9Wgtqyl9FxbCC2mcqLzx5ngJkw38kqUSUi7WjVUqm0UJDi328OpTVAqXuYDFIiRdSEw1o4SVQNZJF8oEs+s5JLSjvW1VsAtWtPTWqRV7Luj0afQaZnqIELvmBiWw3SGlF1tcDkRpU0/BUq58d+koZLM4i+hZVyd3NbwTDcEvg9SE3I7BRhJk6ETLrHWpThNAzPxwo1Pu1V9OigElnOIxF9cozSkOf5AalRk/s/o7qPWCvHoUCTwQ+plH0x9NclQv/nb9OyjZjyyt0V+UPOtBS9NpJt5+nrOs7ntEPR65vBmoEnY0p+FqxEYWwG5nnk1NTf9I2qRAhmdfzbXj4PCfkvVYQJakPGZ6VMsYv0U7VpZM6pQYSmtMX/fFDrtZ8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
