package:
  name: libxcb-cos7-aarch64
  version: 1.13

source:
  - url: http://mirror.centos.org/altarch/7/os/aarch64/Packages/libxcb-1.13-1.el7.aarch64.rpm
    sha256: 723c1a24b8c4638414796e67f446b519a002df5e0481e106da845e684a40614e
    folder: binary
  - url: http://vault.centos.org/7.6.1810/os/Source/SPackages/libxcb-1.13-1.el7.src.rpm
    folder: source

build:
  number: 1
  missing_dso_whitelist:
    - '*'



outputs:
  - name: libxcb-cos7-aarch64
    build:
      noarch: generic

    about:
      home: https://xcb.freedesktop.org/
      license: MIT
      license_family: MIT
      summary: "(CDT) A C binding to the X11 protocol"
      description: |
        The X protocol C-language Binding (XCB) is a replacement for Xlib featuring a
        small footprint, latency hiding, direct access to the protocol, improved
        threading support, and extensibility.
