travis:
  secure:
    BINSTAR_TOKEN: d7t1220A0DHN8FUimY6pN+t3+zhXjspHRrVSSBUsRxwDsZLMSACjTcPmkL45wLI9ZNuIXJRsguoOmgUzFEclIV65QO1ub+Op5uHCpQ7lU6EYECl76ynOIjDKi4kxB429kXOBeznKWWZqvMtAEM8hUXjGzZVb1XpJtWPfYwt849XrPzUYbILTQQtit+HjBZMbicmrsLZG4x/xX7whyofgZPgL/tDF91d0nkpXxSF655XdZKg80IfGfvHHsrfaFcIPkc0Hqdr3bRKNQkiOrFMHTh1QFnHTXPgUMmnY6UHj/nm2hbf0quCVi6X4H1x6zwP35MpszQFTD0SvwrJSrOq5rJ39WsM2/gvoyS2HnlQrSoh4Udc/iZewtpi6JUoejxRkmNgRFPhXnpNa6tmv5PjFAyIqnj2h45dEa+kq6+MFLw5V2TEuT/o1ShjSPcJkjCnSSTYUe1ya7cC/i5p7zKJxLyHD6DD3WTV0gY8+MStoCcnHExzJ9R7WbddQI9iZJRzUcHpQZA6HfkMVCrWnLnPhs9GKFf+XxNWDd2wkkL0r0/TfIYNaOGop4O0Lp/KpaTkkTkeQyHPf3ylmYI9xZS+b8t6/836KwOVmTZPd3tteI3YbVnvqY8OJ+dYIU0geq1GfLwbkGFJgciD/X1WX4JufPZzhEoSjoX5A05pz47YILoY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
