travis:
  secure:
    BINSTAR_TOKEN: pScav7Hu6A6DsXyBme5Q/Trm1VF5iTLqsYB3EcvKfLYOhwTuKVUuMsFLi/037S21myAoL1vyRUvKwmG7wEFq3S2M/V0+E0p2g+iUlyNDkOmH8kCnWro/vUJMrSSLaGGmhh625JMzttbim7d+iR+xjbHsqcOTRCZR8/ClDq5pCa2yoU/uapyTHr4BnYt05ktSfk+6/SNQi1vJSlMQX2xk+RC82zDDWtAGbSztfOxS8MmqJt64m5WyWiZeJf1iozUVux2CQMCh3yfTqcip87Cx4ujsb2DpfhuuiOmU2VYybj6as+qF7KBDXLu8baS1pPcqtVb/RFF4DlDnhbdifoEMIsM1PD4Ht/RR0zctpdNEvtX7KmqofiVSFzHAbtxCTyuf80AmCGWoJ7g7w8ZIaaJVL/WQ5q1qIl/badVgyH0+fyAAU7P03dkyb/eemaFIUs4bgl4srkO8ryWcFC4W8D9s6d7SuYqmHo4Ux8OHDsFo6ipjXT+90/6ej4yV33SNwnaQNkNCGbzk4vmQURjI8ZHLE28KWRJygcbGUeEKcttZ1DdkXsTiv3XIuFqoMMeHzq3EMq3O6ANM4nuYtbfHRphrnAU+zth8cnUCUTAZWkQImNgpAYQluzrBl+a6zm6DzYgS5iYP/JR2zCw45kD1RDjpYkrgBGlleyePxXYqUkUKcP4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
