{% set version = "3.12.2" %}
{% set major_minor = '.'.join(version.split(".")[:2]) %}

package:
  name: cmake
  version: {{ version }}

source:
  - url: https://cmake.org/files/v{{ major_minor }}/cmake-{{ version }}.tar.gz
    sha256: 0f97485799e51a7070cc11494f3e02349b0fc3a24cc12b082e737bf67a0581a4
    patches:
      - 0001-librhash-requires-libdl-for-dlopen.patch

    # Note, on Windows, we *do* build from source, but not fully. We use CMake's own CMakeLists.txt
    # There is not really any good reason to do it this way but it is what it is.
  - url: https://cmake.org/files/v{{ major_minor }}/cmake-{{ version }}-win32-x86.zip       # [win32]
    sha256: fde814282b798a8064aab8c44ddf2f7a25e1139b5a2b3a255adedacfca5706cd                # [win32]
    folder: official-binary                                                                 # [win32]

  - url: https://cmake.org/files/v{{ major_minor }}/cmake-{{ version }}-win64-x64.zip       # [win64]
    sha256: 25c8dbe3e81095463b0d6ccefd836275791299502e3ed5eccf695e118a6d031b                # [win64]
    folder: official-binary                                                                 # [win64]

build:
  number: 0
  skip: True  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make                   # [unix]
  host:
    - bzip2                  # [unix]
    - xz                     # [unix]
    - zlib                   # [unix]
    - expat                  # [unix]
    - libcurl                # [unix]
    # May be good to do this, but really build tools are too critical to risk any DSO incompat.
    # - libarchive             # [unix]
    - ncurses                # [unix]
    # May be good to do this, but really build tools are too critical to risk any DSO incompat.
    # - libuv                  # [unix]
    - rhash                  # [unix]
  run:
    - rhash                  # [unix]

test:
  files:
    - SSLTest.cmake
  commands:
    - cmake --version
    - cmake -V -P SSLTest.cmake
    - ctest --version
    - cpack --version

about:
  home: http://www.cmake.org/
  license: BSD 3-clause
  license_family: BSD
  summary: CMake is an extensible, open-source system that manages the build process
  description: |
    CMake is an open-source, cross-platform family of tools designed to build,
    test and package software.
  dev_url: https://gitlab.kitware.com/cmake/cmake/
  doc_url: https://cmake.org/documentation/
  doc_source_url: https://github.com/Kitware/CMake/blob/master/README.rst

extra:
  recipe-maintainers:
    - blowekamp
    - groutr
    - jakirkham
    - jschueller
    - ocefpaf
    - mingwandroid
    - msarahan
    - scopatz
    - tadeu
