travis:
  secure:
    BINSTAR_TOKEN: BuA6MXzBRbF1OYD/ckgShtIbY99hS2Au4fLgDQwETvF7YrNhn/jvYHEsZQwNPdSMqn1xck1ksgV80CJHL4M3uDpA1UVfKt7bzqlaf/179kTlEnsK8gxRuloRaPJkU03LL9T2AQuD/Iy4xp4bmPfO0p7c5jDx/0YZbH5DMGHbO5Cbr5CqIRfPUk4fk+Cp88bkTvoXKUoz+M6ERBpgSdLxWM9vhg572B65zRAgCetYm023YSaTDDBlX9a/RWn5bmYgLXA1vaxYIYHMUfiaE86DTsgFYy9fVe+OctfWM2cHtcNcUYo5rWmbA19IJIMnNOOzPuUZL61iu5d3e7KtLk2c7vFwkOtm3GSFu/aE7XHpfyCv6d3fH8PKof36qevK4wtwY2xjqvDvFw5BiKKOR79fE05RTW3Mkj3X0d5qwOmy84pdhaTSP1qRjsq26dV5EKtJvIGAK/PfsFoTHIOdtbTy2tpFSiWLS45Ywb/aTfqCsQbGQ3gmZ2tXMspEBIPMzHBfONBi/ghPw/CxrUEqh41QLVePo8JFAOkjYCm0GqFVLPR/kC4hJnH1XUIaZRcc0lhTx8bs27DWb8UEsginKwDkXIV7lPuLJ475RZHonjW0j5mHqT5gpsEWIjlvQiHXRVo6kuXRykskmCSQmq/b6Z1t53I/FL2bBSUgLAHay1bzBz4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
