travis:
  secure:
    BINSTAR_TOKEN: MwODoChXRxcvRgTJre6fRYtbyf1YqRYI0flsb1Rzvd0cW5m153H9mSddqXustpqiHUQXKRe9yJsU7Oo5uh1qVppa1hltJau8GQ8r/CHKwYPD8hFnmVj2GzWQB2KxFxImvMzUWdNS8aiYw5cyiNvCYio1vqD7yymSe1iVIQSHM/KoWRHXcC1CDmbFDM0L7M1e2e4xBJd1B7Yp97b4ngLEJcRMfd9ugjwcSNi+qMPypicGKwt49mqjtoDDmEBRcCf4ppFIHdL9hvRVHwa/O3/Dv3yg4LeJtfelrbvZ2/X4/Df2ETRfyvn9X9V72t0ywXQ234nX0o8/4XVb+NZW0eFAmbWZUdHYwq4RdM8jp5F6yBr6VXZFApoUHnrQOoOIl2+9WE54OTfG+xe0I4A+5We74UZUL1Ch7GOfu7CGgaTGWXbB5TQjmJHz4e5hwywdsysjGzqsN4qny1DFyDCXRdZyu3FZA3EeYzghR8lH1vH+JobeXM3Ymk/OPLNyMqpCmnWgPcvTsmc9CyNwhWp0f52us1ht9ybUK/v/gFktDAoe4trS1Rlfmm2+bFxIwdlzpLWVGKMctRR8Mck/5EOCxny0L8dUZY2IOVJJc8auWhW6Celh6BxY+jzRPG6TCAQW1ZHlclc5EfrnNchRyYs/Llt/5+PB8qBV0p9zvzDRe3XeUDk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
