travis:
  secure:
    BINSTAR_TOKEN: JgYg6dMLmN9tH+hgStr37Z7z+S88QMrS0ya+6p4ZzOviKC9PMcLm6crZbeHxDZfT1NCgJrHehJ8L/pgWHAwloMj9rs8WZ13idWO96gupMp0pAwyXO0jn+dv6xOtkDU2iDG4bZ60eqjwkkCvbe9DsBXIP2pQzrWRzk10orevKmCRPisUUgG6oEy8gwhDtL5zdxoYM+DepQxINgtVA2sOKUCLni1f5AU+1LowZIEoIiw0ubYKM5kIYvfdabcVNNYyxIjey8OYumAzKuAujTPY34VXrbk3WcoupCxxwTCR/XVcPChvIVmK2xG77DvidhVSvd9Q6oRzWanN1FHRriwWKZ4PO1+rBthchAjToHaZo5WWgF6//Nvp1ZDRxUx4vTgi5kpjHKW4gIC6wJcWgKMQgqWkccocJRIzIgFTvIrVsWIG26R3zT6rlAEMrtPQJIW34cJ8mt5/f9V06kcMhNHcvUMbdoGIGIQeVoItrAPs6HmFThjENIYlvgDCjbnVA+UcYFZK+tkRRf1Otvp8zrd6RnZ94ihf7wHxmiYq8YAFHkk9zqzyxEudnOHDzcpo5I9rXS/BLUAk2wRu3zSv2o+AuINCLR88fzvdU7LceV1FXZTUtSgU/7kalr7KU7qb2r6PC40lzEhwWRZns2wfb/AoaA3EFw8M9WiS89RwRtjEPVOQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
