travis:
  secure:
    BINSTAR_TOKEN: NmhdONCanS1K1xW0eL/UzQ2Gn4E+K8R6GmxRiGdzPJwKa5qVzVk8+yt1LIU338klSaeHBmuhYtzROAimp1NQ0AMJRn9ja7EdAQxoZVkMTHVZ2sfUe51A5HbIUsuUFVKnTtQIGcIE3lUGgva0HwMTf38ssU50OKlU0biHHY3mG1pgos22byT37Bt3Pxozpno0QppLEoVD0ksa0kzeM8rOtoa11ftbDD/LLFMQocAJ5egi3x4aArBuCk3qJkVWRG8qdf2ymu5GcT7LqhxWZk6Zsr9CkMG1zeLfkl4Mpqe33bVtNhkCTSb318C//aatuQ1PehQtL8/MWAXQAaUgo0ZZY2N22Rc96QWbNJ8IgelE7j5w+G/19vKHG46JtI6yZJj50XLWc/JK+p2vZAxGNLsoJvIA08wRxa62eT7KXPHIcy2JQP6fgWvytcjvZQzgMt/zr3QBgaCo07LiWQkyIYUNYLtl6xxAY8N5oyTg5or8uWj9e2RV8vOx5i1+zu+Us8sBBuqdqkIZqtOZLyhgG0dKsK/VcxMiXQe1aG48PVBw/9hz4huXfacQxnnRd1eYYZMcryUIw9G98v/OhMzIq9aPmK9eumABz30Ly4iE3AxfwQcbPERAQLxM7LAbhkq5EE5w7RGa4C/V/c803S3h2nMqOrjr1MV6+DPTmVGgKJl8dzs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
