travis:
  secure:
    BINSTAR_TOKEN: HjFxo96/5DgjIsuTfZtTQFBt3IEg0nEjvlPmJCnebs83iHJXu8TmkhiV/UfWQdTjGslNx2kh+uzNUtUpEeh4/m+9dvj/ITx9B2ZqEfJufcSr1Bxdgr+Z4TOFx302KGQQcR0L+U8EcxBOv6DyfAv4kyoMch5xFJicjMv7BdPz6gDga+fLcyDgq0sdhA5CzPzTNRRxHz8xnwP8dmzY5bD2zN+CzAKuifP1NWgHpgflWpFqjdakP3tq66ThI580wpsKNMN9kMNz2HXDz6HLT5EcIHGJcD59Jmo/eax1O1ubzhtn3yL9mm49flSlCyn6dgEIeLhBTOnkn1JxguNddFxQSs+U3qivi0vmTZsdbqRtdzO6sKXnwAhgbrU/8PjHQhvfZTb6+z8nDBXz4N12zpoQvNGlGXueHgazJ08ls2IT6necIGDX3qSOOyeBJ/6TCEsjKSotdx+mxON7z5qOsPNrp4h55tEdwaNWwHJdQQlegujiegmjZOzw1i63kVy3ld0fBsG6zrVVk2+KXlqD1c6qbnebp/dSnsHs6fEIHBH7LlGrdqo/vTdKlm+kSu0y+ybUV0BL833LkCwI2JAFm0KmKPpcZUKGGfnIXMA6zthpHYaQdPvtGMN1OKhufCOsmLkyM2yZ6FnejkjUog1JB6XnY6eU3Vd9PneaCEnq1o1OZlE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
