travis:
  secure:
    BINSTAR_TOKEN: Q7cwT5KF0ZKLjEU59dVS0KpzUIGN/vILQ9HY6xNZJDXWVFp5M6UqAFGzZeLrNwRzUs2Mf8Pcfg1bKVdjWSQCMBKPT3oGzPnbJamvsQUw+CbFDcVxVdocckevRhcOLeiFEludLo8MbMz/iJKVETZDmRLClivVgpgVCik3juWZdudnVIvPpYG/6wgsfzaKof11WV5/341lkG/vzViktPZChjzCoEoh87lGBtFMFqNtOin84x3RZR0mzEP5wkOMVBteFghdGV2nZBWLTc+eU+sr2YlXlpCpAJ++NY3U2FS1GodAj1huXMPqiHM906nVrNO9Fw7nlczwKTx22hMYtUdcA6n5s4T8ByRQKlVJOMgcKQK+EY50+o9kbV9f/Cijeb82Mt49rJeWPXg7mCjKQ6BQeN9a2/XsQ5RjNPCjMl9uNR4YycBxqE969F4RuHFxmsHQphJ8cjckIrznQWE70rZhtrwgzD53kogTx3yfkZ+b5q9gQDOoWbt5cG8gPV0F1E5LkXK1UOx7ZYcOlEgiWiQ1o97S9RebY7NvHiLNVc96jHgxMImQf0qJ18CU+EEeFS4+WbFrfaHEeq5T+jE31hPiyuCX8yyqQSq/OWhDMsGJPwCt/nRT43vtqHJoF4PIdPL6+6JXUMr0yxaB4EgSLiRxirQN7mxa+aJ7O4KcyDCj0YI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
