travis:
  secure:
    BINSTAR_TOKEN: zfFDJTd6rQ5fwpppqVBsuExzAZm5qkxwJsx0zHwgo9dd4ZElVmbZrc3x7+TD6Wz04rzM6qZ9oXDIMc/XWh4IXTpvCkJEZRUqKFvtaRWSz9j2jk0ycUQQ2WVeKAl/h1qYjiIFd+hfybJ2Ko82CUd28gMOZfgGpAagHf6w+0ptKDkwsdZ2SBO6pugKjlxMxf0lqKwC5am/BlNf5hldyzwnzWH67vhaEEQ05kLbSfAesjvrxvXqwrMgdJK95oNSdqUYZoDhWy8Rufr8IW0kvXWVeTvJO+/cB8CNt23L7W/eiPpzxHevvMRTKOo4rhRD8xumrE/qyQiH7a1Jhq3gG+8k6OZoY1GFc5A5gF/us1dvvFwH9/wYVUhLLrwRLAfKWcUt1d5ImQFE7wGZfC+MQSFp8i3oDEKWO2E0mP4bcAYT1F1OVO3oU4G2LWdyZMGPv5K+o4sr1ne+6cHeHSVBSYR8TxRCHsxRZiV3SE6vyr3Fydf4BmOCkvL4bh2s7b85T+kd6ZLMr+xfosg0YT4uUHAgnwTmaGfqGuj3Tnv8oqfYt9fq0RMvrZebFbRSLp4U2YW5lZjF0GMQRDw4uVhSgwNRLv0qIWSBEE8irPZu+kKIvGMIiDVK6yrpOTXwrz6rsEFY8ns91JXsbwjcTqOXXpBEjp4BTXm/yZeJ3zen/If9apw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
