travis:
  secure:
    BINSTAR_TOKEN: Zixybyem0xiuvOuWLPs8movYu02hdS9EN/ZO28QKC7xpuSyjeP/KXctr/B4EBhwc7yhjvee0Skb4lb6O4ta7ipWXuiBr2TTzp542Ubbz7i8qEOqkvIckl3V5NOjtK02ajbaOj7vnnPJRfNSZlSlbAdXLyQXTXG/S8b5WDJdhvt+yIN5GCLNQpxpiy64OLG/MeMVhR5q04U6cHWrXlOyK6cc8Jt9fwXGMrI8fvpaA0L1K6rRm09hnBEp6yGXbpIkaWdNTPJ/8kb/ir922Dx7xZds8n2imGXauSEYZBjdKBdx2h4oR/hA2VUg3atJw02mUUj4ZCvANiFTsIdR2pN26LqMVQQz2FZKipnk+YUDxv/6XPkyeyS8jMqJ/IvSewlRcWBj8DM4TZ7lhFd/YMwln/478YGnYDcWxDedz+41YmcgypdDMlRWmB3JBL/JZDpbpH8OdidBtC/uEQ5WSJDg9gmPwzzM2Tf+mAVlhMDKLllfc1XXEeoin5pja0Zdx2QLtmi6UOMXIPUY2IyHBFrlnWFy7AQdrEpAJiusz0nIYOd9vvS22qxyFzRwS/2scxJto4gLF/X+u62DE8rwp25OKemGNOZGcNujDMJauaHmZGZgzy5Oj8boCgh/pXay06abQQpwGSP4aDldrVZRZDu9N6CPl83ClgvwiCewdxUPQwjE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
