travis:
  secure:
    BINSTAR_TOKEN: leJJDJLUa7e02P0AKEP7OidPlDc9icbCAl6MAYKU1zZ79UycEsFw4nrCujDPYIX06Gfl7ctrfH38bLZ/4OsCdLBpfgDQCY8M9xrR0VgMN0g66aMKZYKdrCshjyzbs4giTe6eedlHyo1QDG+715b5/SjakrtQ4+T/Q8n6o+PNs4IhVsJz4KFt16JLkf78oGr/y+PBrj32M0x+J63AwPKpUkbFQ6JaSPon4btk6FErNGmbForha/0x0pmCSjsYv+jYEkV3JSDr44zF1e91yU3ri9+AYrf+5a05UHAeSCF6zkiR99wxTOZGrzSEDlgAA3bQhn3dqjLuYhiOCl/rKddeXpLs6KwWa/ORBXaPoQyyL5PgWxp31tq1B2WNfHKNCDEuyQAKxgXPQy0ejy5PdSxRRmSw+/xLcxc/fL1vsrOVnGJwahZVip9l+jvyocnCCrE5d8md2uqRHFSU6JokACKdkeka/9AKt56ySJko9FiI+/kNDRNOLAZnZslwMGRl6GZb1RCD+Aj5h7qqx8GTQN0zVZ+Flmx2jcocUghsUJg7z2LR7b6S/bUUJ5ItWHc2D30JyFJcUGutxlW5cbhodZpCzsKRJSfXEXEkYEYuORm2pNgiO/nxYr/yRZzC7aGG8wiLQ7iw0bP9vCSihXMrfL2JJS8wrUq6aopNZ91Nf59zYu8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
