travis:
  secure:
    BINSTAR_TOKEN: uHdksGVqEZzOjXk3nSv+DKdyTJK7Q+dkzge1WxZNVHCYgxgaCiFN0awqvb49ToYYDoz1ggntiRZdDRWaC1gbBcewrXAwKzq85exThcv8s9IJk4OkoEOPbNRZhA9q0boIBX21uNsTiikhXjK80jbeO8hxLg3l0H21wt4w1HBRQ9D1UUBlPjpFx6Tg8OSzNtpK5fcWRdVH2HVHk8D8tl+y11tr5BjbvZ3dWvDTfEfOkUlpw7l4oYultOFQB2Lm9Ni3r1Z1qcPZfE54Dr1OLYOZNX4nQcI5mxm6lvSmQLnBj0awECpTkPnq2cqo/CVbhG8CG0+maTh4XoZ5shvqUc05MEDGCPpj7TqIntzgDN5l5o46ep00W24c85MfiIxxf/hFhuTWWFqStTMUCUTG+fu34dMdR2LWHDauOFm+vp/6/jCmlnF+eO5xbHWVaEQR210MxNUb/F9iHOxK6KS0kX5qxpsHh2K+eBXvlWztkir4+Osd8k3Zku/1u1cc3x414tU+pR0hI5s/rncQ4Y9CqF1vVv2ZqsKpVnI/hP32P4LnwpPWfRbWKuZNvp0230vG2wpng/c2TtZpSDcW1J1CfasnYM4zxCR0D7dl6xr1UQyxEFpaDxE1eNzZAkpFRWW7fs/3NC93luX23pa+yITcAvMix7VRxstRkK7NWSo6/Zd1NWY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
