travis:
  secure:
    BINSTAR_TOKEN: ESqTE7RBbzln+oKOWSEcxoY61E7Y+wrgH/47FT8Nf1jiq91oJkheQZEAOx4I7L95tMX06ub5nLudEqQvRGod+HrYJxILFh9kwW/188HxnFbttSBiCWzRG22d1eZJWgIKXaieniGj39sUXwsX1nSy93MXyMNiAIAnKU/vTZpbq8bCEPdC3ELRxdKwsS5ctobM8hvrz0XojuNZev8Za3cTl0CjgAhsA78Dsp7DU77t3u+JVJlUVyZ7cMHvVuZ9oTAS9Qbmy0JIMwUMKo2Cfn5bXO2LGeXq4vyKniaqZ/1jmmRfYuJYfOi5lLFtxQhnexC9inlvW5PRiyLy8IFuhGdhNf0lcV80ppHbTfdpGP0l/r+lsVLEpGNXKDF2ePqEn83Q0SYugz21bH32dDD89yul5lzHqWlK7QhDFTEsohRuMoxWtbvE0NLzrK0kwjQnZAAgheSNL0KzXv1Uld6mgJ6jz3YTlQFpZfyvWUR9b2KuCdA/f14PiXKoqO5+btCYYDpdWQ0CTX+VF8BdxpzN0+Q/wr59VBz82SZIAEbgMRYq51kT3W8ygH/SWb2REDyZmLVmt/F9qxvbK60aehehBAY6NT+WCeiGaByLiqCgLIB7fqFhmkjIh9lQT/10sF9eSc6MA4OwQGBZpZdwLRYdRMgL7vB9b0/+uEY1FfhAMxArSAA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
