travis:
  secure:
    BINSTAR_TOKEN: cQgcSD6m+WcfDYTPCbfZJdgT8frqPyrO5BWI4RFDXEWZV6U6AHCrsil1RgKMXjKwy7Tw5ZV1hbDG2PlsIw2IJjeG5s2APdQti+w55IjOVJMatQdnavYLUYcHjx8CjzlhnIqX8Mj7iqp6Zt0nP5O+3B/iXn/AqE2FCo7Xbd27oRHMEWlAFfS8WHMVKRMfxF/Hl1zng8fMCgA6RXclnV0NA9kv28gbsHrTCNimhYCDsioCh42TSri0ojQu6AKgMlfq1uiXXvBFxnjajtsjqSaeOFEvcdIH8eU/CjNXMpija+SQGGTi9vASvnywidLLKxzN0VYcsgbib7MnSKXB6nWdQPijG7Dw1ZfiLvhmlkPgTxBNvpDlEWmdGdbWC/4T5rTXtx3TdScvpCQeeBxPFVT3UwU9x23C0wT/CEronwgTl70IR06KWBr6QmoA0u60zy/7YYMs4qWGUAifHPZx0vR412PrCfUYMhEwpOh4I0Oxvdmp6YDLyZ94HFLHkx0op1xlZwMeWKJbDf1OM7Fv9mj7IJUT9qILsQoDvAZ5MpG4f4Uyd3d1WG5qQwa2KkszFpVg+I/+e8mELxDM0AgI+8X7UOBxAhD111H4JreTYlUPOv0wJlYo4cnAsIXTl6KKaY293PZSwOLE8HpIr9PGIVHPdP7w5UY0WuMILoYP4lYE6Ks=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
