travis:
  secure:
    BINSTAR_TOKEN: vQXjDnPels0i0RbEyDCOco43IxrTbX/atgxnKWhVi6v0lT7CPw+d9RvYPYEcA9aiOoSdgUL00at+BSwyxJ6SszOaaHqg7ojoqWqlYwF2kZ60hVjcAPrYYZIwxo8IeTjkXTKyaWHGc96RnlzFsZVgO1AM9ZQ4/oqXSma5e0CXYaQHbJ8pylKzr0TAtCUxPEXQ5mBGrIIx/jKkUEAc6Byy7a/Dx+xmr7OiGvby2HjHThYzujlKslaDdPXzPdQmZ7nR0JHRK6THETlY9ouPpkMdHB1qwy9rSyBMVQoRm0T/SO0/sMmgTE+XSUf9IfOWNzWDCplIStWgoYZ4ZSKMnUKOX+YdVLr+gokadmuE7R0CM42F0L0FKPzQiempN0wHAk0V2jnncOHE3HE+qXtAcGNAhe3u118BjY37Uvdpj9VLS6A6XuI9ZGBfXf6DFo39Em4VcfMWcJRDkcbYW7W2j/RNxxvFbKnf0ZjM9f7wxpYxw0OBUdIQn4b9bA7zPCLPS3LfBrC4aSSm0HoEoBBpH7lqs0htDasEcCVY268y2/CASZxKRqvtwsuL9Wi+bKYeC2AwLxrml2ktv91wxGMmCXGA9P23Z0jn8s6OP3wVqIamhOWARFQLrNOmQjXIbqWhuQo+6sHM+6LPdML6Axl9ud6+MhG/Pkm/XSO2nxX0OfJi/kM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
