travis:
  secure:
    BINSTAR_TOKEN: hFbkznxZokoY17DaAzhhL4Vh7biZXOJOSVjYBjd2pqtpS4uWwZkyhzVkZdb/nNhJIsgOvzcL527QzQNunP5N5erNf4wdIkHubijiZNPfUISTNudA8ac5ECKPyOAxL9Nn/aFEtSfWCP99kayCCOw1yNHFuHB92YxWyFjVPHwjh5w6czgfU6pkq+F2lRecwhc6o9aR9ZDuZTeoRnlt5BNBClabSoZGfnGyBjolzXsfdw1H++DFnOzbbLbPi1qEXuuXRcETJQA0yC/NhGsTxc7gb/MXzmDhefkko+aY+oFUgftxp80S+CJWJgfTDRb2fsmS97iAYj42CoBTuGAamdyLI5JQVaxI9tLEej9YMTkSyNZLo70CGXBufyI7N9kPzT4o1Mf5nhTpOjDFl89B2gN4PQACSbeB4IEy2ABbn+RDjtrTmzQXz+HnYUiKKzEfmy5OAxK4NSGVr3GqO2Ri6Nt/as7nL7VpHASHTIAHd7iswuFagwDioYrTixov7zzhLLaTXQstPXIdyMMxBflHke5iREBQvagRIdhpiFlPjNdBN6d3keqYMQ++FSnyZI3kopW9ImiAzSNSDIFIJIhi0zttnGtSye5TB20775wYFqN6xfKbh/Dm1QRo2YmV37Pvx8ajqhc23VlgwargPVneNYx0XK3Rt+xgVeSB6YxyyZ1xqco=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
