travis:
  secure:
    BINSTAR_TOKEN: BqTn+GSLRrL6VPXqjtLdQ1R2tdQnr/zymX1U6dNxUmibyq1DoUXFXxLp3oUoZeMhGQIy8vGZMmnb1sBZU+jGRamhaah0+nuokUqneIS8onWhJF4OnOueQr+pxkSvj1++SBdARb+rsuW75mhaFSPc8vjGeqH42bcsTobM6ES61sXVpTG8dcjr/w6/seGsOrMaZySBULBYSPv5+PmT2FjyqL+7ULBXJbPWJFUPJ4cFG+i+qte/qbwUBVzLiUZaBcg6qyg3/q8x64JX9gBnzzzEp5dq2Cb875EbWoOPaxEJ+fV/G8Nz+gzEHMr8iQ+x7Xi/ibJUEz8HhnMmGYYZfXfNQVWJBZM9FVyS5P6/hB86z0frzq8xRJbWudorWi+aGDANT6IJ8ta1VdiVzg1xGFmGdSkzEOx4XWgXy1qZJeSUbd6VwCZdoeVFFK2UqYgmqQdh5yhQYJmIryoCg6q75S2/Re8oEv+cbFxCXfU8ICqwDEv+mgo9nsLNPVI8H7I/GtzkULt3Hc83HMRzk9T6J5BgkrSTTTHLAqaA2yWN9PBDJFsXGWCzRwca7Jtf2EhAHW0TAKQOp18D1He8EIc35EUBQ2doYLmffjqIlLu1GZp9i6IRr4LrncRKZ0+8vIww9ZGIQRS0DgqzBZ+/rdZSYIDe9yhwiriCxEsoz3VyMxb+xtA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
