travis:
  secure:
    BINSTAR_TOKEN: nP2QsIuDmOTYnI8fv6Hfz6xPzpKLsz+hhYKD4530yi7kAIsOGGiLWLKFzdmHslDkLfzGw57vnX8DEdMM3RnpIr4M/m9D2yLQF/3nwiBwhe8uVVka0AoVIdoCxhDNEZJrewPB6ZrvBaEbESrDOKyWhTtsisrv+NHHRYhxwk3rXzvJMMavMfbpwXCZetM78syHMXCwiBjwYf2CeCsd4SuLjDF0g2pCUHXigGj1r/uktM9mGnwzcCl0rBswheeWBdQMv13BMbfhj6FCQmSq3zTDWzHPWmzfXS8K9wrgSUg2X4i2kA1raRZIB5LHai6+D7kK4xE6k75pHiU2rOyGgKlc7mUQZVYdQYDYds5cL7UKnIz9sw89+GgoWN1qs477m6xbpnmHatYBwft1PUaj5cjD/h9BLqii9ZKYTWoWmyIJQVhW0RGJh+4XH/wkSK0nu/I1TVpk/KyBtTzB74hzAJePCWMy642nDORJceIP0o9ndBU5WSlUVHr74zHAtgBcvizwqSPBpMIIeCVqNBJBum3Ss+P2wdlQTt0V65phfvICTw2jlljGnxp/6hcw9BcdHFvdhz8BOnEussFLgiJMxav4yq1589OGZ6is09HGCF32OUzYNzv0fqg2j2jVeLwr4t3NmZWI/vvx0udrkTVs1sQo6OE4JEbf3rIPhJ4BhYTWeN8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
