travis:
  secure:
    BINSTAR_TOKEN: FoEjUHHO/ZMOsz1FKdLWFGT0HVxf7QAk9nAK/ISVC5bzAUTjQAeYNz0PpEWKgk+X4hITluLW+ufJM+vvILvnOjXPR2g42qXpl39j8DdAJZNB58gB4jggg5Iq3HRNRgmVwXZ1HU1OZm3dzRkXNwS6+ewhrevzSEZzYG197aHC8HvyC/oz4w/mmfbJ98YZVY4Sy843FyG29fnBwulPEXZgkVRiry0/yQts1sjh79O+7QB1yM+V9QPKciUkc/sL7tCVZ9OFady7oXsoWvs8XZzhlppTrLzsCQKhslTtm1w2HMdpqxCyRrl39eoWdii39zhbiVlWWDz9Oc6vPqlSI+5Menk23x03UozAKMuIjs4JT/YKdtw1zo00HEc6UjvI0Xi1F4sgpYcFCM1BKRwU6+6y358aaqcBX+vsUhVMpO1pcTr12nq72z6t1D+H1uQukDq+fDfJuQzK1hGUl7DSQPOGOdaWewINoJ5NJzRlE8l1hTfI2sx1ma4iB8098+nFi9UBvr5ueCyzokzzXSA6OMupao87aHVodzqgtKjaDn8/gcCQbOJgis8rZx275DRnwpPPxyukPGZDvPb3Px5cHxe5+hiPhl9hAqE+xo8KNf8QBkP9iVMybeC5781fDf/2gSD6m0KzSUYlDt+kSCZOL2ik0SA5oOB315TkORgsYRoilPs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
