travis:
  secure:
    BINSTAR_TOKEN: wag5E9dNGZsfZ/Fg+odMPkYhNAz/IlDcv15I64FVmG8Cb8Dze34An8kjv+/Kx8AEA80tZKVS3hJ+qxUrj/+WcgEkhA5HHxDgkfVCaY/c/icPbdvm0Xy/Yhyg5UeLfUXkEq2kZr3GWwzardH9tisuqP2hfMDtMt72mSRUyJh4m7olIRjWKDI6GiTvlaGDfQQAY9xhrRvyRi4BPuOSYvyJkQXtKoOg/KywegUtA6t+BERGhLS1D7HOY+APZk9du1b743l9Y473soc+2XpaBy0BoPkllzlXUE2pnQeOczKLb4EK3iT2rJWJZlJJYTQb2lxhGbNuw9O1BmpLHakqoPcqwnmOwtnJ7SlylYAzLDdOnmk0seHYpBaSCBCPn+9fDinUWNovp9srztx05ypKyBBXbKDNpt2000Txdz3tKqj54rtANkhB8YjLSzaYXq9+gRrb06nbEq06n4l4HknqC2cbdvYiHQZbW1J664Q5RqZAPNJOYgw8teLCdJfjsOFQ4F7c9oenxxCxmkZbEKVo1t4Uovk4xXAWnj4Fis/A5ilpaRJF/cNqDXc11gcmLBv5XAFRqahiRNfS0L5HGEfH1uVpeb0MznaN21q+cuJvTVaaKi7WIMWFb0Tyc5NAkaGSuX4UvCBCt91luG50P1J82qOVhdhJrbgXx33cGHCioE6fCWA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
