travis:
  secure:
    BINSTAR_TOKEN: PFiXJ14eiye0z7o+cQV7IWdCrx2x9eCIkC1oQNba7F5uaut894/b5L2mAF8jfFO1xV1XMbknA6TSqh+XydBftAVYy/3e7O9itUUjVTXZvvcv/C9A0SpsZ2BHdsN4+sI234sPsrLWnA2SLl5L4i1LTBftsPVVl1whGMnwrUjYvrxpEUfa3TyuEBRGGDMn//GIbv2MdeS4CsQLGK1c+1CO+yLCDcnOIVT1mQ509gXm+CJ+PLlig5lBN47EMMMFDhqA1dCe2ekS5dBFR++iUaKw8/yScQhK+leM3lSyO8pMdKARRAJMwqGN4ydAtTS+x6+dqgKlAAAXoAoyFWUr+dOAR3lmHi0pUqGJpPdV/18kmdadUtVl4L8SxJXDek6XZxRt0XuG1oKXaow/Jkl22KzOp3EYu8Ow3t2GMGdpjuclC6YVZuiC9Df+eZ6fvOCNotDUUPfWzqRp/bvOP0H9CYz60wUuwXnxQRkZPPeRIblm5MCVbnMSN0G7WIcM8JYfJM01SUch3hHyiD59eOCyt/3/qEXLEAM9tlrxeVfNaUt5OJiiQx5wal0k9u7LcJGpbTf7lpJv1EnGqKvBUvY9z2x7GW9uufbTYFBncezQgtfdfkDDWQdlPwo6yxnupMu+a0x7F6ojEulm72/KCrMyqn8C5Pk21rDbpE4kxn1AQQL1iTI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
